source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LIHQRScanner_Example', :exclusive => true do
  pod 'LIHQRScanner', :path => '../'
end

target 'LIHQRScanner_Tests', :exclusive => true do
  pod 'LIHQRScanner', :path => '../'

  
end
